# Generated by Django 4.1.3 on 2022-11-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('maxWeight', models.CharField(max_length=10)),
                ('flightTime', models.CharField(max_length=3)),
                ('altitude', models.CharField(max_length=10)),
                ('armed', models.BooleanField()),
                ('image', models.CharField(max_length=500)),
                ('owner', models.CharField(max_length=100)),
            ],
        ),
    ]
