# Generated by Django 4.1.3 on 2022-11-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihalar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ihaFrom', models.CharField(max_length=200)),
                ('ihaTo', models.CharField(max_length=200)),
                ('iha', models.CharField(max_length=3)),
            ],
        ),
    ]
